server {
    server_name api.beastreaderone.com;

    location / {
        proxy_pass http://localhost:8081; # Port where PM2 node server runs
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        
        # Increase timeouts for long-running websocket connections
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }
}